title: Learning
author: Wayne Butterworth
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
A simple site to learn and experiment with Markdown and Github pages

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
